PLAYERS = {
    'GOALKEEPERS': {
        "Jan Oblak": 91,
        "ter Stegen": 90,
        "Manuel Neuer": 90,
        "Donnarumma": 89,
        "Alisson": 89,
        "Courtois": 89,
        "Ederson": 89,
        "Keylor Navas": 88,
        "Szczesny": 87,
        "LLoris": 87,
        "Casteels": 86,
        "Handanovic": 86,
        "Schmeichel": 85,
        "Gulacsi": 85,
        "Sommer": 85,
        "Emi Martinez": 84,
        "De Gea": 84,
        "Maignan": 84,
        "Onana": 83,
        "Pickford": 83
    },

    'DEFENDERS': {
        "Van Dijk": 89,
        "Ramos": 88,
        "Marquinhos": 87,
        "Alexander Arnold": 87,
        "Robertson": 87,
        "Dias": 87,
        "Chiellini": 86,
        "Koulibaly": 86,
        "Varane": 86,
        "Alba": 86,
        "Laporte": 86,
        "Cancelo": 86,
        "Hummels": 86,
        "Skriniar": 86,
        "De Ligt": 85,
        "Bonucci": 85,
        "Hakimi": 85,
        "De Vrij": 85,
        "Walker": 85,
        "Carvajal": 85,
        "Silva": 85,
        "Digne": 84,
        "Trippier": 84,
        "Acuna": 84,
        "Ricardo Periera": 84,
        "Maguire": 84,
        "Pique": 84,
        "Jesus Navas": 84,
        "Luke Shaw": 84,
        "Ginter": 84,
        "Felipe": 84,
        "Savic": 84,
        "Guerreiro": 84,
        "Jose Gimenez": 84,
        "Alaba": 84,
        "Hernandez": 84,
        "Manolas": 83,
        "Kounde": 83,
        "Wan-Bissaka": 83,
        "Jose Gaya": 83
    },
    'MIDFIELDERS': {
        "De Bruyne": 91,
        "Kante": 90,
        "Kimmich": 89,
        "Casemiro": 89,
        "Son": 89,
        "Bruno Fernandes": 88,
        "Toni Kroos": 88,
        "Muller": 87,
        "Goretzka": 87,
        "de Jong": 87,
        "Verratti": 87,
        "Sancho": 87,
        "Pogba": 87,
        "Modric": 87,
        "Thiago": 86,
        "Fabinho": 86,
        "Coman": 86,
        "Parejo": 86,
        "Busquets": 86,
        "Rodrigo": 86,
        "Bernando Silva": 86,
        "Marcos Llorente": 86,
        "Rashford": 85,
        "Milinkovic-Savic": 85,
        "Ndidi": 85,
        "Gnabry": 85,
        "Papu Gomez": 85,
        "David Silva": 85,
        "Koke": 85,
        "Gundogan": 85,
        "Reus": 85,
        "Jorginho": 85,
        "Fekir": 84,
        "Tielemans": 84,
        "Fernando": 84,
        "Henderson": 84,
        "Luis Alebrto": 84,
        "Sane": 84,
        "Kostic": 84,
        "Sabitzer": 84
    },

    'ATTACKERS': {
        "Messi": 93,
        "Lewandowski": 92,
        "Ronaldo": 91,
        "Neymar": 91,
        "Mbappe": 91,
        "Harry Kane": 90,
        "Salah": 90,
        "Benzema": 89,
        "Mane": 89,
        "Suarez": 88,
        "Sterling": 88,
        "Haaland": 88,
        "Lukaku": 88,
        "Immobile": 87,
        "Dybala": 87,
        "Aguero": 87,
        "Di Maria": 87,
        "Vardy": 86,
        "Insigne": 86,
        "Gerard Moreno": 86,
        "Mahrez": 86,
        "Aubameyang": 85,
        "Firmino": 85,
        "Cavani": 85,
        "Oyarzabal": 85,
        "Memphis": 85,
        "Greizmann": 85,
        "Lautaro": 85,
        "Hazard": 85,
        "Aspas": 84,
        "Tadic": 84
    }
}